//-------+---------+---------+---------+---------+---------+---------+---------+
// Copyright (c) 1990-1991 Betz Associates. All rights reserved.
//
// File Name: INPUT.H
// Project:   Flights of Fantasy
// Creation:  March 10, 1992
// Author:    Mark Betz (MB)
//
// Machine:   IBM PC's and Compatibles
//
// Includes:  nothing
//
//-------+---------+---------+---------+---------+---------+---------+---------+
// Change History
// ------ -------
//
//      Date            Rev.	Author		Purpose
//      ----            ----    ------      -------
//      4-10-1992       1.0     MB          initial development
//      8-29-1992       1.1b    MB          first beta
//      9-26-1992       1.1     MB          publication release
//      10-12-1995      2.0     mracky      update
// Description
// -----------
//      Function prototypes and data definitions for the flight simulator
//      user input routines.
//
//-------+---------+---------+---------+---------+---------+---------+---------+

#ifndef INPUT_H
#define INPUT_H_

#ifndef AIRCRAFT_H
#include "aircraft.h"
#endif

#endif

